[tool.poetry]
name = "yacc"
version = "0.1.0"
description = "swap cases"
authors = ["urm8"]
license = "LICENCE"
packages = [
    { include = "yacc", from="src" }
]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.8 || ^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^20.8b1"
pylint = "^2.7.4"
dephell = "^0.8.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
